pipeline{
  agent none
  stages{
    stage('build and test'){
      agent{
        docker{image'node:16-alpine'}
      }
      steps{
        sh 'node --version'
      }
    }
    stage('build, test and execute'){
      agent{
        docker{image'python:3'}
      }
      steps{
        sh '''
           python --version
           cd multi-stage-multi-agent/python
           python3 main.py
        '''
      }
    }
  }
}

