pipeline{
  agent{
    docker{
      image'python:3'
    }
  }
  stages{
    stage('build, test and execute'){
      sh ''' 
          python --version
          echo ' hello world!'
      '''
    }
  }
}
      
