pipeline{
  agent{
    docker{image'python:3'}
  }
  stages{
    stage('build, test and execute'){
      steps{
      sh ''' 
          python --version
          echo ' hello world!'
      '''
    }
  }
}
}
      
